<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="FluentAssertions" Version="8.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.18" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Indica.Productivity.Shared\Indica.Productivity.Shared.csproj" />
    <ProjectReference Include="..\Indica.Productivity.Application\Indica.Productivity.Application.csproj" />
    <ProjectReference Include="..\Indica.Productivity.API\Indica.Productivity.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="FileParserTests\Samples\**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\database.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
